Initial Commit
Uniswap/routing-api pull request #47
Opened 2022-06-02 08:09 UTC by raghava-pamula

Initial Commit for adding support for web3 providers outside of infura. Currently, the project only supports infura web3 providers, and more flexibility is needed since infura has had outages.

https://github.com/Uniswap/routing-api/issues/38

2022-06-02 13:07 UTC, willpote reviewed
Looks good. One minor comment, and then just let me know when you are able to get the integ tests passing then I'll approve

2022-06-02 13:07 UTC, willpote commented on lib/handlers/injector-sor.ts
> +          // todo: todo: add logic to generate moralis rpc urls
Could you fill in alchemy just so its ready if we need to switch out?

Think we can remove moralis too for now

2022-06-03 02:04 UTC, raghava-pamula commented
Integ tests are failing :'(

2022-06-05 00:47 UTC, willpote requested changes

2022-06-05 00:47 UTC, willpote commented on bin/app.ts
> +      jsonRpcProviders[key] = jsonRpcProvidersSecret.secretValueFromJson(key) as unknown as string
Use `.toString()` like we do below

2022-06-05 00:47 UTC, willpote commented on bin/app.ts
> +  },
Can you update the package README so people know to do this?

2022-06-05 00:47 UTC, willpote commented on lib/handlers/injector-sor.ts
> +        log.info({ url: url }, `GENERATED URL`)
Lets remove this log

2022-06-05 00:47 UTC, willpote commented on lib/handlers/injector-sor.ts
> +        if (typeof url == undefined || url == '') {
Just `!url` is fine

2022-06-05 00:47 UTC, willpote commented on bin/app.ts
> +      //backup Arn: arn:aws:secretsmanager:us-east-2:644039819003:secret:routing-api-rpc-urls-json-backup-D2sWoe
Could you add a bit more context to this comment so other people know why this exists? 

Also add a note that you must update the multicall chunk size to 50  for optimism when switching to the backup

2022-06-05 15:51 UTC, willpote approved these changes

2022-06-05 17:29 UTC, merged