fix: filter out expired routes by ttl in the RoutesDB read path
Uniswap/routing-api pull request #544
Opened 2024-04-02 22:41 UTC by jsy1218

In prod, we noticed that the RoutesDB can return cached routes, that we can no longer query from RoutesDB:

![Screenshot 2024-04-01 at 3 49 39 PM](https://github.com/Uniswap/routing-api/assets/91580504/934a3cd7-b52b-4931-be07-5d8350b3ef57)

From https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html, "You can still update the expired items that are pending deletion, including changing or removing their TTL attributes". This can explain why the expired routes can still get returned from RoutesDB and used in router for quoting.

2024-04-02 22:43 UTC, rollingtumbling approved these changes
When the record get written to DB, does it have TTL set already?

2024-04-02 22:44 UTC, jsy1218 commented
> When the record get written to DB, does it have TTL set already?

That's right. It's written [here](https://github.com/Uniswap/routing-api/blob/c71d31bd040b18186c3d87e5692000327538d77f/lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts#L394).

2024-04-02 23:16 UTC, mikeki approved these changes

2024-04-02 23:36 UTC, cgkol reviewed
Can we add a test please?

2024-04-02 23:36 UTC, cgkol requested changes
let me change this

2024-04-02 23:43 UTC, cgkol commented
@rollingtumbling @mikeki reminder to make sure we enforce tests especially on change that affect production

2024-04-03 16:35 UTC, jsy1218 commented
> Can we add a test please?

Added an integ-test, that actually cached routes into the RoutesDB dynamo DB, and then use the `mockdate` library to make sure the system time shifts to one later later, so that retrieving the cached routes can be actually filtered due to the TTL expiry.

2024-04-26 15:17 UTC, cgkol reviewed
Lets make sure @mikeki gets to see it too!

2024-04-26 16:04 UTC, jsy1218 commented
> Lets make sure @mikeki gets to see it too!
> 
> 

@mikeki I actually wonder if we still need to have this fix in? Because this was believed to fix https://uniswapteam.slack.com/archives/C021SU4PMR7/p1711827069423259 at beginning, but the root cause turned out to be something else.

2024-05-30 18:05 UTC, mikeki commented on lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
> +              record.ttl >= Math.floor(Date.now() / 1000)
I believe this should be:
```
record.ttl >= Math.floor(Date.now() / 1000) && (
  !record.protocol || protocols.includes(record.protocol)
)
```

2024-10-16 23:17 UTC, jsy1218 commented
very wrong fix, now that we know why cached routes can become stale in RoutesDB

2024-10-16 23:17 UTC, closed without merging